/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hallio.gui.windows;

/**
 *
 * @author yeohp
 */
public class admindashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public admindashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        exitbtn = new javax.swing.JButton();
        staffmanagementbtn = new javax.swing.JButton();
        viewcustomerbookingbtn = new javax.swing.JButton();
        myprofilebtn = new javax.swing.JButton();
        usermanagementbtn = new javax.swing.JButton();
        admindashboardlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        staffmanagementbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        staffmanagementbtn.setText("Staff Management");
        staffmanagementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffmanagementbtnActionPerformed(evt);
            }
        });

        viewcustomerbookingbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewcustomerbookingbtn.setText("View customer bookings");
        viewcustomerbookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcustomerbookingbtnActionPerformed(evt);
            }
        });

        myprofilebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myprofilebtn.setText("My Profile ");
        myprofilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myprofilebtnActionPerformed(evt);
            }
        });

        usermanagementbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usermanagementbtn.setText("User Management");
        usermanagementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermanagementbtnActionPerformed(evt);
            }
        });

        admindashboardlabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        admindashboardlabel.setText("Admin Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(myprofilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(usermanagementbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(viewcustomerbookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(staffmanagementbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(admindashboardlabel)))
                                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(admindashboardlabel)
                                .addGap(38, 38, 38)
                                .addComponent(staffmanagementbtn)
                                .addGap(31, 31, 31)
                                .addComponent(usermanagementbtn)
                                .addGap(38, 38, 38)
                                .addComponent(viewcustomerbookingbtn)
                                .addGap(38, 38, 38)
                                .addComponent(myprofilebtn)
                                .addGap(33, 33, 33)
                                .addComponent(exitbtn)
                                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {
        loginGUI.main(null);
        this.dispose();
    }

    private void staffmanagementbtnActionPerformed(java.awt.event.ActionEvent evt) {
        staffmanagement.main(null);
        this.dispose();
    }

    private void viewcustomerbookingbtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void myprofilebtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void usermanagementbtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel admindashboardlabel;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton myprofilebtn;
    private javax.swing.JButton staffmanagementbtn;
    private javax.swing.JButton usermanagementbtn;
    private javax.swing.JButton viewcustomerbookingbtn;
    // End of variables declaration
}
